{{- if .Values.httpRoute }}
{{- range .Values.httpRoute }}
{{- $routeName := .name }}
{{- $gatewayName := .gatewayName }}
{{- $gatewayNamespace := .gatewayNamespace }}
---
kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: {{ $routeName }}
  labels:
    gateway: {{ $gatewayName }}
spec:
  parentRefs:
    {{- if .redirectHTTP }}
    {{- $redirects := .redirectHTTP }}
    {{- $redirectList := ternary $redirects (list $redirects) (kindIs "slice" $redirects) }}
    {{- range $redirectList }}
    - name: {{ $gatewayName }}
      {{- if $gatewayNamespace }}
      namespace: {{ $gatewayNamespace }}
      {{- end }}
      sectionName: {{ .httpsListenerName | default "https" }}
    {{- end }}
    {{- else }}
    - name: {{ $gatewayName }}
      {{- if $gatewayNamespace }}
      namespace: {{ $gatewayNamespace }}
      {{- end }}
    {{- end }}
  rules:
    {{- toYaml .rules | nindent 4 }}
{{- if .redirectHTTP }}
{{- $redirects := .redirectHTTP }}
{{- $redirectList := ternary $redirects (list $redirects) (kindIs "slice" $redirects) }}
{{- range $redirectList }}
---
kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: {{ $routeName }}-{{ .httpListenerName | default "http" }}-redirect
  labels:
    gateway: {{ $gatewayName }}
spec:
  parentRefs:
    - name: {{ $gatewayName }}
      {{- if $gatewayNamespace }}
      namespace: {{ $gatewayNamespace }}
      {{- end }}
      sectionName: {{ .httpListenerName | default "http" }}
  rules:
    - filters:
      - type: RequestRedirect
        requestRedirect:
          scheme: https
{{- end }}
{{- end }}
{{- if .redirectHost }}
{{- range .redirectHost }}
---
kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: {{ $routeName }}-{{ .listenerName }}-redirect
  labels:
    gateway: {{ $gatewayName }}
spec:
  parentRefs:
    - name: {{ $gatewayName }}
      {{- if $gatewayNamespace }}
      namespace: {{ $gatewayNamespace }}
      {{- end }}
      sectionName: {{ .listenerName }}
  rules:
    - filters:
      - type: RequestRedirect
        requestRedirect:
          scheme: {{ .redirectScheme }}
          hostname: {{ .redirectHostname }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}