apiVersion: v2
name: snipeit
version: 4.0.1
appVersion: v8.0.4
description: A free open source IT asset/license management system
keywords:
  - snipeit
  - inventory
  - asset management
home: https://snipeitapp.com
icon: https://snipeitapp.com/img/logos/snipe-it-logo-xs.png
sources:
  - https://github.com/PurseChicken/helm-charts
  - https://github.com/snipe/snipe-it

dependencies:
  - name: mysql
    version: ^1.0.0
    repository: https://storage.googleapis.com/t3n-helm-charts
    condition: mysql.enabled
  - name: mysql-backup
    version: ~1.0.1
    condition: mysql-backup.enabled
    repository: https://storage.googleapis.com/t3n-helm-charts