{{- if .Values.monitoring }}
{{- $allowResourceDeletion := .Values.allowResourceDeletion }}
{{- $projectName := include "cnrm-chart.projectID" . }}
{{- range .Values.monitoring }}
{{- if .notificationChannel }}
{{- range .notificationChannel }}
---
apiVersion: monitoring.cnrm.cloud.google.com/v1beta1
kind: MonitoringNotificationChannel
metadata:
  annotations:
    {{- include "cnrm-chart.cnrmAnnotations" (dict "projectName" $projectName "allowResourceDeletion" $allowResourceDeletion) | nindent 4 }}
  name: {{ include "cnrm-chart.resourceName" (dict "projectName" $projectName "name" .name) }}
spec:
  type: {{ .type }}
  {{- if .displayName }}
  displayName: {{ .displayName | quote }}
  {{- end }}
  {{- if .labels }}
  labels:
    {{- toYaml .labels | nindent 4 }}
  {{- end }}
  {{- if .sensitiveLabels }}
  sensitiveLabels:
    {{- toYaml .sensitiveLabels | nindent 4 }}
  {{- end }}
  {{- if hasKey . "description" }}
  description: {{ .description | quote }}
  {{- end }}
  {{- if hasKey . "enabled" }}
  enabled: {{ .enabled }}
  {{- end }}
{{- end }}
{{- end }}
{{- if .alertPolicy }}
{{- range .alertPolicy }}
---
apiVersion: monitoring.cnrm.cloud.google.com/v1beta1
kind: MonitoringAlertPolicy
metadata:
  annotations:
    {{- include "cnrm-chart.cnrmAnnotations" (dict "projectName" $projectName "allowResourceDeletion" $allowResourceDeletion) | nindent 4 }}
    {{- include "cnrm-chart.customAnnotations" (dict "annotations" .customAnnotations) | nindent 4 }}
  name: {{ include "cnrm-chart.resourceName" (dict "projectName" $projectName "name" .name) }}
  {{- if .labels }}
  labels:
    {{- toYaml .labels | nindent 4 }}
  {{- end }}
spec:
  resourceID: {{ .resourceID | default .name }}
  displayName: {{ .displayName | quote }}
  {{- with .documentation }}
  documentation:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if hasKey . "enabled" }}
  enabled: {{ .enabled }}
  {{- else }}
  enabled: true
  {{- end }}
  {{- if .severity }}
  severity: {{ .severity }}
  {{- end }}
  {{- if .notificationChannels }}
  notificationChannels:
    {{- range .notificationChannels }}
    -
{{ include "cnrm-chart.gcpObjectRef" (dict "projectName" $projectName "ref" .) | trim | indent 6 }}
    {{- end }}
  {{- end }}
  combiner: {{ .combiner }}
  {{- if .alertStrategy }}
  alertStrategy:
    {{- toYaml .alertStrategy | nindent 4 }}
  {{- end }}
  conditions:
    {{- toYaml .conditions | nindent 4 }}
{{- end }}
{{- end }}
{{- if .uptimeCheckConfig }}
{{- range .uptimeCheckConfig }}
---
apiVersion: monitoring.cnrm.cloud.google.com/v1beta1
kind: MonitoringUptimeCheckConfig
metadata:
  annotations:
    {{- include "cnrm-chart.cnrmAnnotations" (dict "projectName" $projectName "allowResourceDeletion" $allowResourceDeletion) | nindent 4 }}
    {{- include "cnrm-chart.customAnnotations" (dict "annotations" .customAnnotations) | nindent 4 }}
  name: {{ include "cnrm-chart.resourceName" (dict "projectName" $projectName "name" .name) }}
  {{- if .labels }}
  labels:
    {{- toYaml .labels | nindent 4 }}
  {{- end }}
spec:
  {{- if .projectRef }}
  projectRef:
    {{- if .projectRef.external }}
    external: {{ .projectRef.external | quote }}
    {{- end }}
    {{- if .projectRef.name }}
    name: {{ .projectRef.name | quote }}
    {{- end }}
    {{- if .projectRef.namespace }}
    namespace: {{ .projectRef.namespace | quote }}
    {{- end }}
  {{- else }}
  projectRef:
    external: projects/{{ $projectName }}
  {{- end }}
  displayName: {{ .displayName | quote }}
  timeout: {{ .timeout | quote }}
  {{- if .resourceID }}
  resourceID: {{ .resourceID | quote }}
  {{- end }}
  {{- if .period }}
  period: {{ .period | quote }}
  {{- end }}
  {{- with .contentMatchers }}
  contentMatchers:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .selectedRegions }}
  selectedRegions:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .monitoredResource }}
  monitoredResource:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .httpCheck }}
  httpCheck:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .tcpCheck }}
  tcpCheck:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .resourceGroup }}
  resourceGroup:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
{{- if .monitoredProject }}
{{- with .monitoredProject }}
---
apiVersion: monitoring.cnrm.cloud.google.com/v1beta1
kind: MonitoringMonitoredProject
metadata:
  annotations:
    {{- include "cnrm-chart.deletionPolicy" (dict "allowResourceDeletion" $allowResourceDeletion) | nindent 4 }}
  name: {{ include "cnrm-chart.resourceName" (dict "projectName" $projectName "name" .name) }}
spec:
  metricsScope: {{ .name }}
  resourceID: {{ $projectName }}
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}